### ISSUE TITLE
hcdeathalertschannel sets itself as channel 1 on login

### ISSUE THREAD

**Issue by rsquires1988** [aaronma37/Deathlog#36]
This causes all other channel numbers to be pushed up by one, breaking macros and 20 years of /1 /2 muscle memory.  Preferably, it would be moved to the end of the chat channels.  This can be done in-game using the chat settings UI to drag the channel to the end of the list, which doesn't break the addon, thankfully.  I haven't found anyone else having this problem, so I'm not entirely sure if this is widespread or not.

**Comment by rsquires1988** [comment]
#37 Submitted a pull request that fixes the issue by leaving the channel, and rejoining after 1 second on login.  hcdeathalertschannel is now last on the list and no longer claims the /1 spot after a game restart.

**Comment by rsquires1988** [comment]
> This causes all other channel numbers to be pushed up by one, breaking macros and 20 years of /1 /2 muscle memory. Preferably, it would be moved to the end of the chat channels. This can be done in-game using the chat settings UI to drag the channel to the end of the list, which doesn't break the addon, thankfully. I haven't found anyone else having this problem, so I'm not entirely sure if this is widespread or not.

Did end up finding someone else with the issue in the [curseforge comments](https://www.curseforge.com/wow/addons/deathlog/comments)

**Comment by rsquires1988** [comment]
This seems to only work most of the time.  A longer delay might improve the chance that it doesn't fail.

**Comment by aaronma37** [comment]
@rsquires1988  hey I merged the PR; should this be closed?

**Comment by rsquires1988** [comment]
It only seems to work sometimes. I'm not sure yet if upping the amount of time is a fix or not. I'll fiddle with that and see if I can get it to work more consistently.

**Comment by rsquires1988** [comment]
Upping the time seems to have helped it stick more consistently, but it still doesn't fix it for first log in on a new character.

**Comment by aaronma37** [comment]
Thanks again @rsquires1988
