### ISSUE TITLE
Chat Channel changes

### ISSUE THREAD

**Issue by mootkins** [aaronma37/Deathlog#51]
Can we get deathlog to stop changing its chat tab position to 1? I want local to be 1, trade to be 2, but every single session it gets changed for hcdeathalertschannel to be 1, and pushing the others aside.

I then have to go and manually set it to 7/8, but itll revert if i ever log out.

![image](https://github.com/aaronma37/Deathlog/assets/54551598/9e123ab0-9cb2-43f8-81a9-d7ac8c6843f6)
The above is what is happening.

![image](https://github.com/aaronma37/Deathlog/assets/54551598/95740ede-2e80-4400-a414-b50e9e67d31c)
This is how I manually set it every session

**Comment by aaronma37** [comment]
Sorry for the hassle; its being investigated. Did this always happen for you?

**Comment by aaronma37** [comment]
Also does /resetchat help?

**Comment by aaronma37** [comment]
This should be fixed in 0.1.7.  If not, feel free to re-open

**Comment by mootkins** [comment]
Updated to latest via github, still puts deathlog channel at 1, have to manually move to lower.  Does not save channel locations.

Still not working
